### ISSUE TITLE
Structure

### ISSUE THREAD

**Issue by TrySound** [artem-malko/tars-handlebars#1]
Add `compile-templates.js` to `tars/tasks/html` for more strictly modules.

**Comment by artem-malko** [comment]
:+1: 
В 1.3.0 будет.

**Comment by TrySound** [comment]
`handlebars-helpers.js` тоже надо переместить в этот репозиторий. Тогда папку tars буду полностью копировать.

**Comment by artem-malko** [comment]
:+1:

**Comment by artem-malko** [comment]
Issue создал.
